version: "3.5"
services:

  linuxmuster-bdc:
    build: .
    container_name: linuxmuster-bdc
    restart: always
    hostname: ${HOSTNAME}
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "88:88/tcp"
      - "88:88/udp"
      - "135:135/tcp"
      - "389:389/tcp"
      - "389:389/udp"
      - "445:445/tcp"
      - "636:636/tcp"
